import { createHmac, timingSafeEqual } from 'node:crypto';

export interface TelegramInitDataUser {
  id: number;
  username?: string;
  first_name?: string;
  last_name?: string;
}

type VerifyResult = { ok: true; user: TelegramInitDataUser } | { ok: false };

// initData is regenerated by the Telegram client every time the Mini App is opened, so this is
// generous headroom against clock drift rather than a real session length — not a "log the buyer
// out after a day" mechanism.
const MAX_AGE_SECONDS = 24 * 60 * 60;

// Validates the signature Telegram attaches to WebApp.initData, per the documented Mini Apps
// algorithm (https://core.telegram.org/bots/webapps#validating-data-received-via-the-mini-app).
// This is the only place in the app that establishes a Telegram user's identity server-side
// instead of trusting whatever initDataUnsafe.user the client reports — needed for the "Мої
// замовлення" read (api/orders.ts's `mine=1` branch), the first endpoint that returns one
// person's private data (past orders) scoped by Telegram identity rather than gated by the
// separate admin Google-session check.
export function verifyTelegramInitData(initData: string, botToken: string): VerifyResult {
  if (!initData) return { ok: false };

  const params = new URLSearchParams(initData);
  const hash = params.get('hash');
  if (!hash) return { ok: false };
  params.delete('hash');

  const dataCheckString = [...params.keys()]
    .sort()
    .map((key) => `${key}=${params.get(key)}`)
    .join('\n');

  const secretKey = createHmac('sha256', 'WebAppData').update(botToken).digest();
  const computedHash = createHmac('sha256', secretKey).update(dataCheckString).digest('hex');

  const providedHashBuf = Buffer.from(hash, 'hex');
  const computedHashBuf = Buffer.from(computedHash, 'hex');
  if (providedHashBuf.length !== computedHashBuf.length || !timingSafeEqual(providedHashBuf, computedHashBuf)) {
    return { ok: false };
  }

  const authDate = Number(params.get('auth_date'));
  if (!authDate || Date.now() / 1000 - authDate > MAX_AGE_SECONDS) return { ok: false };

  const userRaw = params.get('user');
  if (!userRaw) return { ok: false };
  try {
    const user = JSON.parse(userRaw) as TelegramInitDataUser;
    if (typeof user.id !== 'number') return { ok: false };
    return { ok: true, user };
  } catch {
    return { ok: false };
  }
}
